'use client';
import {useState} from 'react';
import {cloud} from '@/lib/cloud';
import {useWorkspace} from './WorkspaceState';
import WorkspaceBackup from './WorkspaceBackup';
export default function Account(){const {user,status,ready,member,refresh}=useWorkspace();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function login(signup=false){if(!cloud)return;setBusy(true);try{const {error}=signup?await cloud.auth.signUp({email,password}):await cloud.auth.signInWithPassword({email,password});setMessage(error?error.message:signup?'请查收验证邮件，验证后用邮箱和密码登录。 / Verify your email, then sign in.':'登录成功 / Signed in');}catch{setMessage('无法连接，请重试 / Connection failed');}finally{setBusy(false);}}
 return <div className="content"><header className="page-header"><p className="eyebrow">MY ACCOUNT</p><h1>我的账号 / Account</h1><p>手机、电脑、iPad 使用同一账号，笔记和日程随身同步。</p></header><section className="panel auth-panel">{!cloud?<div className="notice">云端同步尚未配置。日程、文字和链接可先保存在本机；配置完成后，可登录并迁移到账号。 / Cloud setup pending. Local notes and calendar work now.</div>:!ready?<p>连接中…</p>:user?<><h2>{user.email}</h2><p>{member?'IMBA 班级成员 / Class member':'个人账号 · 班级权限待管理员开通 / Personal account'}</p><p role="status">{status}</p><div className="button-row"><button className="button" onClick={()=>void refresh()}>立即同步 / Sync now</button><button className="button secondary" onClick={()=>void cloud!.auth.signOut()}>退出 / Sign out</button></div></>:<form onSubmit={e=>{e.preventDefault();void login();}}><label>邮箱 / Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>密码 / Password<input type="password" autoComplete="current-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="button-row"><button className="button" disabled={busy}>登录并同步 / Sign in</button><button type="button" className="button secondary" disabled={busy||!email||password.length<8} onClick={()=>void login(true)}>创建学生账号 / Register</button></div><p role="status">{message}</p></form>}</section><div className="notice">个人笔记只对你可见。班级内容须通过成员验证；注册账号不会自动获得班级权限。</div><WorkspaceBackup/></div>;
}
