'use client';
import {useState} from 'react';
import {cloud} from '@/lib/cloud';
import {useWorkspace} from './WorkspaceState';
import WorkspaceBackup from './WorkspaceBackup';
import {useLanguage} from './Language';
export default function Account(){const {user,status,ready,member,refresh}=useWorkspace();const {language}=useLanguage(),en=language==='en';const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function login(signup=false){if(!cloud)return;setBusy(true);try{const {error}=signup?await cloud.auth.signUp({email,password}):await cloud.auth.signInWithPassword({email,password});setMessage(error?error.message:signup?(en?'Check your verification email, then sign in.':'请查收验证邮件，验证后用邮箱和密码登录。'):(en?'Signed in':'登录成功'));}catch{setMessage(en?'Connection failed. Please retry.':'无法连接，请重试');}finally{setBusy(false);}}
 return <div className="content"><header className="page-header"><p className="eyebrow">MY ACCOUNT</p><h1>{en?'My account':'我的账号'}</h1><p>{en?'Use one account to sync notes and your schedule across phone, computer and tablet.':'手机、电脑、iPad 使用同一账号，笔记和日程随身同步。'}</p></header><section className="panel auth-panel">{!cloud?<div className="notice">{en?'Cloud sync is not configured yet. Your calendar, notes and links can be saved locally until it is connected.':'云端同步尚未配置。日程、文字和链接可先保存在本机；配置完成后，可登录并迁移到账号。'}</div>:!ready?<p>{en?'Connecting…':'连接中…'}</p>:user?<><h2>{user.email}</h2><p>{member?(en?'IMBA class member':'IMBA 班级成员'):(en?'Personal account · class access pending':'个人账号 · 班级权限待管理员开通')}</p><p role="status">{en?status.split(' / ').at(-1):status.split(' / ')[0]}</p><div className="button-row"><button className="button" onClick={()=>void refresh()}>{en?'Sync now':'立即同步'}</button><button className="button secondary" onClick={()=>void cloud!.auth.signOut()}>{en?'Sign out':'退出'}</button></div></>:<form onSubmit={e=>{e.preventDefault();void login();}}><label>{en?'Email':'邮箱'}<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{en?'Password':'密码'}<input type="password" autoComplete="current-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="button-row"><button className="button" disabled={busy}>{en?'Sign in & sync':'登录并同步'}</button><button type="button" className="button secondary" disabled={busy||!email||password.length<8} onClick={()=>void login(true)}>{en?'Register':'创建学生账号'}</button></div><p role="status">{message}</p></form>}</section><div className="notice">{en?'Private notes are visible only to you. Class content requires membership verification; registering does not grant class access automatically.':'个人笔记只对你可见。班级内容须通过成员验证；注册账号不会自动获得班级权限。'}</div><WorkspaceBackup/></div>;
}
