'use client';
import {useState} from 'react';
import Link from 'next/link';
import {knowledge} from '@/lib/knowledge';
import {aiEnabled,cloud} from '@/lib/cloud';
import {useWorkspace} from './WorkspaceState';
export default function Bilingual(){const [text,setText]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[direction,setDirection]=useState('en');const {user,member}=useWorkspace();const matches=knowledge.filter(k=>(k.zh+' '+k.en).toLowerCase().includes(text.toLowerCase()));async function translate(){if(!cloud||!user||!member||!aiEnabled)return;setBusy(true);setResult('');try{const {data,error}=await cloud.functions.invoke('mba-translate',{body:{text,target:direction}});setResult(error?'翻译暂不可用，请稍后重试。 / Translation unavailable.':data?.translation||data?.error||'未返回结果');}catch{setResult('连接失败，原文已保留。 / Connection failed.');}finally{setBusy(false);}}
 return <div className="content"><header className="page-header"><p className="eyebrow">SAY IT CLEARLY</p><h1>双语表达 / Bilingual desk</h1><p>术语、知识点和案例，用两种语言说清楚。</p></header><section className="translation-desk"><label>术语 / 案例原文 · Source text<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={6000} placeholder="输入术语，或粘贴需要翻译的案例与表达…"/></label><div className="button-row"><select aria-label="目标语言 / Target language" value={direction} onChange={e=>setDirection(e.target.value)}><option value="en">地道英文 / English</option><option value="zh">自然中文 / Chinese</option></select><button className="button" disabled={!aiEnabled||!user||!member||busy||!text.trim()} onClick={()=>void translate()}>{busy?'翻译中…':'翻译 / Translate'}</button>{!aiEnabled?<span className="meta">自由文本 AI 翻译待开通 / AI setup pending</span>:<Link href="/account">{member?'班级账号 · 每日最多 50 次':'登录并核验班级身份以使用 AI'}</Link>}</div>{result&&<p className="translation-result" role="status">{result}</p>}</section><p className="storage-note">已内置双语术语、概念和案例，无需登录。启用 AI 后，主动提交的原文将发送至 OpenAI；不自动发送个人笔记或课件。 / Built-in bilingual content is available now. AI sends only the text you submit.</p><div className="section-heading"><h2>双语术语与案例</h2><small>{matches.length} 个概念</small></div><div className="bilingual-grid">{matches.map(k=><article className="panel" key={k.id}><h3>{k.zh}</h3><p className="english-name">{k.en}</p><p>{k.definitionZh}</p><p lang="en">{k.definitionEn}</p><details><summary>案例 / Example</summary><p>{k.exampleZh}</p><p lang="en">{k.exampleEn}</p></details></article>)}</div></div>;
}
