'use client';
import Link from 'next/link';
import {useState} from 'react';
import {catalog} from '@/lib/catalog';
import {safeUrl} from '@/lib/planner.mjs';
import {useWorkspace} from './WorkspaceState';
import {cloud} from '@/lib/cloud';
export default function Capture(){const ws=useWorkspace();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(!ws.ready)return;const link=String(f.get('link')||'');if(link&&!safeUrl(link)){setMessage('请输入 HTTPS 链接');return;}setBusy(true);try{const category=String(f.get('category'));const personal=['路上随想 / Thought','错题记录 / Mistake','个人总结 / Summary'].includes(category);const visibility=personal?'private':String(f.get('visibility')) as 'private'|'class';const data={title:f.get('title'),text:f.get('text'),course:f.get('course'),category:f.get('category'),link};const file=f.get('file') as File;let path='';if(file?.size){if(!cloud||!ws.user)throw Error('请先连接云端并登录以保存文件 / Connect and sign in to upload files');if(file.size>20*1024*1024)throw Error('文件须小于 20MB');path=ws.user.id+'/'+crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const upload=await cloud!.storage.from('mba-materials').upload(path,file);if(upload.error)throw upload.error;}
 const id=crypto.randomUUID();if(await ws.put(id,'capture',{...data,file:path,fileName:file?.size?file.name:''},visibility)){form.reset();setMessage(ws.user?'已保存并同步 / Saved & synced':'已保存到此设备 / Saved locally');}else{setMessage('记录未保存，请重试 / Record not saved');if(path)await cloud!.storage.from('mba-materials').remove([path]);}}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function openFile(path:string){const {data,error}=await cloud!.storage.from('mba-materials').createSignedUrl(path,60);if(error)setMessage(error.message);else window.open(data.signedUrl,'_blank','noopener,noreferrer');}
 return <div className="content"><header className="page-header"><p className="eyebrow">CAPTURE NOW, CONNECT LATER</p><h1>随手记 / Quick capture</h1><p>课堂要求、提交入口、路上的一个想法，先放进来。</p></header><div className="capture-grid"><form className="panel event-form" onSubmit={save}><label>标题 / Title<input name="title" required maxLength={180} placeholder="例如：Accounting Reflection 要求"/></label><div className="form-pair"><label>课程 / Course<select name="course">{catalog.courses.map(c=><option value={c.slug} key={c.slug}>{c.title}</option>)}</select></label><label>分类 / Type<select name="category"><option>路上随想 / Thought</option><option>课程要求 / Requirement</option><option>Reflection</option><option>Homework</option><option>错题记录 / Mistake</option><option>课堂笔记 / Class note</option><option>个人总结 / Summary</option></select></label></div><label>补充内容 / Note<textarea name="text" maxLength={100000} placeholder="不用整理成文章，先记下关键内容。"/></label><label>要求 / 提交链接 · URL<input name="link" type="url" placeholder="https://"/></label><label>课表 / 资料文件 · File<input name="file" type="file" disabled={!ws.user} accept=".pdf,.ppt,.pptx,.doc,.docx,.txt,.md,.json,.ics"/><small>最多 20MB，需连接云端并登录。文字和链接可先本机保存。文件不会加入公开网站。</small></label><p className="meta">随想、个人总结和错题始终仅个人可见。 / Thoughts, summaries and mistakes stay private.</p><label>可见范围 / Visibility<select name="visibility"><option value="private">仅个人 / Only me</option>{ws.member&&<option value="class">仅班级 / Class</option>}</select></label><button className="button" disabled={!ws.ready||busy}>{busy?'保存中…':(ws.user?'保存并同步 / Save & sync':'保存到此设备 / Save locally')}</button>{!ws.user&&<Link href="/account">登录以跨设备同步 / Sign in to sync</Link>}<p role="status">{message||ws.status}</p></form><section><div className="section-heading"><h2>最近收集 / Recent</h2><Link href="/calendar">添加到日历 ↗</Link></div>{!ws.records.some(r=>r.kind==='capture')&&<p className="panel">这里会按时间收纳你的要求、链接和想法。</p>}{ws.records.filter(r=>r.kind==='capture').map(r=><article className="capture-card" key={r.id}><span className="pill">{r.visibility==='private'?'仅个人':'仅班级'} · {String(r.data.category||'')}</span><h3>{String(r.data.title)}</h3><p>{String(r.data.text||'')}</p>{r.data.link&&safeUrl(String(r.data.link))?<a href={String(r.data.link)} target="_blank" rel="noreferrer">打开链接 / Open link ↗</a>:null}{r.data.file?<button className="text-button" onClick={()=>void openFile(String(r.data.file))}>{String(r.data.fileName)} ↗</button>:null}{r.owner===ws.ownerId&&<button className="text-button danger" onClick={async()=>{if(confirm('删除记录？文件如有将保留在个人资料库。 / Delete record?'))await ws.remove(r);}}>删除记录</button>}</article>)}</section></div></div>;
}
