'use client';
import Link from 'next/link';
import {catalog} from '@/lib/catalog';
import {knowledge} from '@/lib/knowledge';
import {deadline} from '@/lib/planner.mjs';
import {eventTitle,useEvents} from './Planner';
import {useLanguage} from './Language';
import {useWorkspace} from './WorkspaceState';
import {useNow} from './useNow';
export default function SemesterHome(){
 const {language}=useLanguage(),en=language==='en',ws=useWorkspace(),events=useEvents();
 const now=useNow();
 const upcoming=events.filter(e=>!e.done&&Date.parse(e.end)>now).slice(0,4);
 const tasks=events.filter(e=>!e.done&&e.kind!=='class');
 const today=now?new Date(now).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}):'';
 const week=today?Array.from({length:7},(_,index)=>{const date=new Date(Date.parse(`${today}T00:00:00Z`)+index*86400000);return {key:date.toISOString().slice(0,10),date};}):[];
 return <div className="content semester-home"><header className="semester-hero"><div><p className="eyebrow">FUDAN IMBA · YOUR LEARNING WORKSPACE</p><h1>{en?'Less searching.\nMore understanding.':'少一点翻找，\n多一点理解。'}</h1><p>{en?'Know what is next. Connect what you learn. Capture what matters.':'知道下一步要做什么，让每一次学习都有落点。'}</p><div className="button-row"><Link className="button" href="/calendar">{en?'Open my calendar':'查看课程日历'} ↗</Link><Link className="button secondary" href="/capture">＋ {en?'Capture a thought':'记下一个想法'}</Link></div></div><aside><span className="hero-term">2026<span>FALL SEMESTER</span></span><div className="hero-metrics"><div><strong>09</strong><span>{en?'courses connected':'门课已建知识地图'}</span></div><div><strong>{String(knowledge.length).padStart(2,'0')}</strong><span>{en?'bilingual concepts':'个双语核心概念'}</span></div></div><p>{en?'Confirmed timetable · Shanghai time':'真实课表已更新 · 上海时区'}</p></aside></header>
 <div className="priority-grid">{[['01','/calendar',en?'Your semester at a glance':'课程日历',en?'Classes, requirements and deadlines. Export to your own calendar.':'上什么课、交什么、何时截止，一处看清。','▦'],['02','/map',en?'Ideas that connect':'知识地图',en?'Prepare, understand and review across nine courses.':'九门课串起来，边理解边补记。','◇'],['03','/bilingual',en?'Think in both languages':'中英表达',en?'Concepts and illustrative cases, side by side.':'术语、知识点与案例，中英对照。','文']].map(([n,href,title,desc,icon])=><Link className="priority-card" href={href} key={n}><div><span className="eyebrow">{n}</span><span className="priority-icon" aria-hidden="true">{icon}</span></div><h2>{title} <span>↗</span></h2><p>{desc}</p></Link>)}</div>
 <section className="home-week panel" aria-label={en?'Next seven days':'未来七天课程'}><div className="section-heading"><div><p className="eyebrow">{en?'NEXT 7 DAYS':'未来 7 天'}</p><h2>{en?'Your week at a glance':'本周课程，一眼看清'}</h2></div><Link href="/calendar">{en?'Full calendar':'完整日历'} ↗</Link></div>{week.length?<div className="home-week-grid">{week.map(day=>{const dayEvents=events.filter(event=>event.start.slice(0,10)===day.key);return <article className={day.key===today?'today':''} key={day.key}><header><span>{day.date.toLocaleDateString(en?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',weekday:'short'})}</span><strong>{day.date.getUTCDate()}</strong></header><div>{dayEvents.slice(0,3).map(event=><Link href="/calendar" key={event.id}><time>{event.start.slice(11,16)}</time><b>{eventTitle(event,en)}</b>{event.audience==='elective'&&<small>{en?'Elective':'选修'}</small>}</Link>)}{!dayEvents.length&&<span className="no-class">{en?'No class':'无课'}</span>}{dayEvents.length>3&&<small>+{dayEvents.length-3}</small>}</div></article>;})}</div>:<p className="meta">{en?'Loading your calendar…':'正在读取课程日历…'}</p>}</section>
 <div className="home-agenda-grid"><section className="panel"><div className="section-heading"><h2>{en?'Next on your calendar':'接下来'} <span className="status-dot"/></h2><Link href="/calendar">{en?'Full calendar':'完整日历'} ↗</Link></div>{upcoming.length?upcoming.map(e=><Link className="home-event" href="/calendar" key={e.id}><time>{new Date(e.start).toLocaleDateString(en?'en-GB':'zh-CN',{timeZone:'Asia/Shanghai',month:'short',day:'numeric'})}</time><div><h3>{eventTitle(e,en)}</h3><p>{e.location||catalog.courses.find(c=>c.slug===e.course)?.code}</p></div><span>→</span></Link>):<div className="home-empty"><span>▦</span><h3>{en?'No upcoming classes':'接下来暂无课程'}</h3><p>{en?'Add a personal class or deadline when your plan changes.':'如有新增选修课或截止事项，可随时补充。'}</p><Link href="/calendar">{en?'Add an event':'添加日程'} →</Link></div>}</section><aside className="panel"><p className="eyebrow">A CLEAR NEXT STEP</p><h2>{en?'Deadlines to keep in mind':'把截止日期放在心上'}</h2>{tasks.length?tasks.slice(0,3).map(e=><Link className="home-deadline" href="/calendar" key={e.id}><b>{eventTitle(e,en)}</b><span>{deadline(e).days<0?(en?'Overdue':'已逾期'):deadline(e).days+' '+(en?'days left':'天后截止')}</span><progress max={100} value={deadline(e).percent} aria-label={en?'Time elapsed':'时间进度'}/></Link>):<p>{en?'Homework, reflection and exam countdowns will appear once dates are added.':'添加作业、Reflection 和考试日期后，这里显示时间进度。完成状态由你单独标记。'}</p>}<div className="home-sync"><small>{ws.user?'CLOUD WORKSPACE':'ON THIS DEVICE'}</small><p>{ws.status|| (en?'Loading your workspace…':'正在读取学习空间…')}</p><Link href="/account">{en?'Account & backup':'账号与备份'} →</Link></div></aside></div>
 <section className="home-courses"><div className="section-heading"><h2>{en?'Your nine courses':'我的九门课'}</h2><Link href="/sitemap">{en?'See the sitemap':'查看全站地图'} ↗</Link></div><div className="course-quick-grid">{catalog.courses.map(c=><Link href={'/courses/'+c.slug} key={c.slug}><span className="course-mini-code">{c.code}</span><div><h3>{c.title}</h3><p>{knowledge.filter(k=>k.courses.includes(c.slug)).length} {en?'connected concepts':'个关联知识点'}</p></div><span>→</span></Link>)}</div></section></div>;
}
