'use client';
import Link from 'next/link';
import {catalog} from '@/lib/catalog';
import {knowledge} from '@/lib/knowledge';
import {deadline} from '@/lib/planner.mjs';
import {useEvents} from './Planner';
import {useLanguage} from './Language';
import {useWorkspace} from './WorkspaceState';
import {useNow} from './useNow';
export default function SemesterHome(){
 const {language}=useLanguage(),en=language==='en',ws=useWorkspace(),events=useEvents();
 const now=useNow();
 const upcoming=events.filter(e=>!e.done&&Date.parse(e.end)>now).slice(0,4);
 const tasks=events.filter(e=>!e.done&&e.kind!=='class');
 return <div className="content semester-home"><header className="semester-hero"><div><p className="eyebrow">FUDAN IMBA · YOUR LEARNING WORKSPACE</p><h1>{en?'Less searching.\nMore understanding.':'少一点翻找，\n多一点理解。'}</h1><p>{en?'Know what is next. Connect what you learn. Capture what matters.':'知道下一步要做什么，让每一次学习都有落点。'}</p><div className="button-row"><Link className="button" href="/calendar">{en?'Open my calendar':'查看课程日历'} ↗</Link><Link className="button secondary" href="/capture">＋ {en?'Capture a thought':'记下一个想法'}</Link></div></div><aside><span className="hero-term">2026<span>FALL SEMESTER</span></span><div className="hero-metrics"><div><strong>09</strong><span>{en?'courses connected':'门课已建知识地图'}</span></div><div><strong>{String(knowledge.length).padStart(2,'0')}</strong><span>{en?'bilingual concepts':'个双语核心概念'}</span></div></div><p>{en?'General concept maps · Actual course dates await import':'通用学习地图 · 真实课表待导入'}</p></aside></header>
 <div className="priority-grid">{[['01','/calendar',en?'Your semester at a glance':'课程日历',en?'Classes, requirements and deadlines. Export to your own calendar.':'上什么课、交什么、何时截止，一处看清。','▦'],['02','/map',en?'Ideas that connect':'知识地图',en?'Prepare, understand and review across nine courses.':'九门课串起来，边理解边补记。','◇'],['03','/bilingual',en?'Think in both languages':'中英表达',en?'Concepts and illustrative cases, side by side.':'术语、知识点与案例，中英对照。','文']].map(([n,href,title,desc,icon])=><Link className="priority-card" href={href} key={n}><div><span className="eyebrow">{n}</span><span className="priority-icon" aria-hidden="true">{icon}</span></div><h2>{title} <span>↗</span></h2><p>{desc}</p></Link>)}</div>
 <div className="home-agenda-grid"><section className="panel"><div className="section-heading"><h2>{en?'Next on your calendar':'接下来'} <span className="status-dot"/></h2><Link href="/calendar">{en?'Full calendar':'完整日历'} ↗</Link></div>{upcoming.length?upcoming.map(e=><Link className="home-event" href="/calendar" key={e.id}><time>{new Date(e.start).toLocaleDateString(en?'en-GB':'zh-CN',{timeZone:'Asia/Shanghai',month:'short',day:'numeric'})}</time><div><h3>{e.title}</h3><p>{e.location||catalog.courses.find(c=>c.slug===e.course)?.code}</p></div><span>→</span></Link>):<div className="home-empty"><span>▦</span><h3>{en?'Start with your first class':'从第一条真实课表开始'}</h3><p>{en?'Import your schedule, or add a class and its requirements.':'导入学生课表，或添加课程与课后要求。系统不会猜测时间。'}</p><Link href="/calendar">{en?'Set up my calendar':'添加课程安排'} →</Link></div>}</section><aside className="panel"><p className="eyebrow">A CLEAR NEXT STEP</p><h2>{en?'Deadlines to keep in mind':'把截止日期放在心上'}</h2>{tasks.length?tasks.slice(0,3).map(e=><Link className="home-deadline" href="/calendar" key={e.id}><b>{e.title}</b><span>{deadline(e).days<0?(en?'Overdue':'已逾期'):deadline(e).days+' '+(en?'days left':'天后截止')}</span><progress max={100} value={deadline(e).percent} aria-label={en?'Time elapsed':'时间进度'}/></Link>):<p>{en?'Homework, reflection and exam countdowns will appear once dates are added.':'添加作业、Reflection 和考试日期后，这里显示时间进度。完成状态由你单独标记。'}</p>}<div className="home-sync"><small>{ws.user?'CLOUD WORKSPACE':'ON THIS DEVICE'}</small><p>{ws.status|| (en?'Loading your workspace…':'正在读取学习空间…')}</p><Link href="/account">{en?'Account & backup':'账号与备份'} →</Link></div></aside></div>
 <section className="home-courses"><div className="section-heading"><h2>{en?'Your nine courses':'我的九门课'}</h2><Link href="/sitemap">{en?'See the sitemap':'查看全站地图'} ↗</Link></div><div className="course-quick-grid">{catalog.courses.map(c=><Link href={'/courses/'+c.slug} key={c.slug}><span className="course-mini-code">{c.code}</span><div><h3>{c.title}</h3><p>{knowledge.filter(k=>k.courses.includes(c.slug)).length} {en?'connected concepts':'个关联知识点'}</p></div><span>→</span></Link>)}</div></section></div>;
}
