'use client';
import {useRef,useState} from 'react';
import {useWorkspace,workspaceKey} from './WorkspaceState';
import {parseWorkspaceBackup} from '@/lib/workspace-backup.mjs';
import {downloadFile} from '@/lib/planner.mjs';
import {parseProgress,storageKey} from '@/lib/progress.mjs';
import type {RecordItem} from '@/lib/cloud';
export default function WorkspaceBackup(){const ws=useWorkspace(),input=useRef<HTMLInputElement>(null);const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function importRecords(text:string){setBusy(true);let count=0;try{const items=parseWorkspaceBackup(text) as Pick<RecordItem,'key'|'kind'|'data'|'visibility'>[];const conflicts=items.filter(i=>ws.records.some(r=>r.owner===ws.ownerId&&r.key===i.key));if(conflicts.length&&!confirm(conflicts.length+' 条同名记录将被导入内容覆盖。先导出备份？取消可返回。 / Replace matching records?'))return;for(const item of items){if(!await ws.put(item.key,item.kind,item.data,'private'))throw Error('保存失败，已完成记录保留 / Save interrupted');count++;}setMessage(count+' 条记录已导入，均设为仅个人 / Imported as private');}catch(e){setMessage(count+' 条已导入；'+(e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function migrate(){try{const local=JSON.parse(localStorage.getItem(workspaceKey)||'[]'),old=parseProgress(JSON.parse(localStorage.getItem(storageKey)||'{"version":2,"reviews":{},"notes":{}}'));const merged=new Map(local.map((r:{key:string})=>[r.key,r]));for(const [id,text] of Object.entries(old.notes))if(!merged.has(id))merged.set(id,{key:id,kind:'note',data:{text,title:'迁移笔记 / Imported note'}});for(const [id,status] of Object.entries(old.reviews))merged.set('review-'+id,{key:'review-'+id,kind:'review',data:{questionId:id,status}});await importRecords(JSON.stringify({version:'1.2.1',records:[...merged.values()]}));}catch{setMessage('本机备份无法读取，原数据已保留 / Unable to read local backup');}}
 return <section className="panel workspace-backup" id="workspace-backup"><h2>工作台备份 / Workspace backup</h2><p>包含新版日历、知识点笔记、收集箱和云端复习记录。备份含个人信息，请勿上传公开仓库。文件仅备份路径，不包含文件本体；跨账号恢复不会转移原文件权限。</p><div className="button-row"><button className="button" disabled={!ws.ready||busy} onClick={()=>downloadFile('IMBA-workspace-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({version:'1.2.1',records:ws.records.filter(r=>r.owner===ws.ownerId)},null,2),'application/json')}>导出工作台 / Export</button><button className="button secondary" disabled={!ws.ready||busy} onClick={()=>input.current?.click()}>导入备份 / Restore</button>{ws.user&&<button className="text-button" disabled={busy} onClick={()=>void migrate()}>本机与旧版记录 → 当前账号</button>}<input ref={input} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>5000000){setMessage('文件不能超过 5MB');return;}await importRecords(await f.text());}}}/></div><p role="status">{busy?'正在逐条保存，请勿关闭页面 / Saving…':message}</p></section>;
}
