'use client';
import {createContext,useContext,useEffect,useState,useCallback,useRef,type ReactNode} from 'react';
import {cloud,type RecordItem} from '@/lib/cloud';
import type {User} from '@supabase/supabase-js';
export const workspaceKey='mba-learning-workspace-v121';
export const localOwner='this-device';
type Store={user:User|null;ownerId:string;records:RecordItem[];ready:boolean;status:string;member:boolean;refresh:()=>Promise<void>;put:(key:string,kind:string,data:Record<string,unknown>,visibility?:'private'|'class',revision?:number)=>Promise<boolean>;remove:(record:RecordItem)=>Promise<boolean>};
const Context=createContext<Store|null>(null);
export function WorkspaceProvider({children}:{children:ReactNode}){
 const [user,setUser]=useState<User|null>(null),[records,setRecords]=useState<RecordItem[]>([]),[ready,setReady]=useState(false),[status,setStatus]=useState(''),[member,setMember]=useState(false);
 const generation=useRef(0),userRef=useRef<User|null>(null);
 const refresh=useCallback(async()=>{const who=userRef.current,g=generation.current;try{if(!cloud||!who){const saved=JSON.parse(localStorage.getItem(workspaceKey)||'[]');if(!Array.isArray(saved))throw Error('Invalid local data');setRecords(saved);setStatus('已保存到此设备 · 尚未跨设备同步 / Saved on this device only');return;}const result=await cloud.from('mba_os_records').select('*').order('updated_at',{ascending:false});if(g!==generation.current)return;if(result.error){setStatus('同步失败 / Sync failed: '+result.error.message);return;}setRecords(result.data as RecordItem[]);setStatus('已同步 / Synced');}catch{setStatus('读取失败，原数据保留 / Unable to load. Original data retained.');}},[]);
 useEffect(()=>{const invalidate=()=>{generation.current++;};if(!cloud){queueMicrotask(()=>void refresh().finally(()=>setReady(true)));const read=()=>void refresh();window.addEventListener('storage',read);return()=>window.removeEventListener('storage',read);}const change=async(who:User|null)=>{generation.current++;const g=generation.current;userRef.current=who;setUser(who);setRecords([]);setMember(false);setReady(false);await refresh();if(who){const result=await cloud!.from('mba_os_members').select('user_id').eq('user_id',who.id).maybeSingle();if(g===generation.current)setMember(!!result.data);}if(g===generation.current)setReady(true);};
  cloud.auth.getSession().then(({data})=>change(data.session?.user||null));const {data}=cloud.auth.onAuthStateChange((_event,session)=>{if(session?.user.id!==userRef.current?.id)void change(session?.user||null);});
  const focus=()=>void refresh();window.addEventListener('focus',focus);const timer=setInterval(focus,30000);return()=>{data.subscription.unsubscribe();window.removeEventListener('focus',focus);clearInterval(timer);invalidate();};
 },[refresh]);
 async function put(key:string,kind:string,data:Record<string,unknown>,visibility:'private'|'class'='private',revision?:number){if(!ready)return false;try{if(!cloud||!user){if(visibility!=='private')throw Error('班级资料需要登录 / Sign in for class content');const saved:RecordItem[]=JSON.parse(localStorage.getItem(workspaceKey)||'[]');const existing=saved.find(r=>r.key===key);if(revision!==undefined&&existing?.revision!==revision)throw Error('其他页面已更新，请刷新后重试 / Changed in another tab');const record:RecordItem={id:existing?.id||crypto.randomUUID(),owner:localOwner,key,kind,data,visibility,revision:(existing?.revision||0)+1,updated_at:new Date().toISOString()};localStorage.setItem(workspaceKey,JSON.stringify([record,...saved.filter(r=>r.key!==key)]));await refresh();return true;}setStatus('同步中 / Syncing…');const existing=records.find(r=>r.owner===user.id&&r.key===key);const fields={kind,data,visibility};const result=existing?await cloud.from('mba_os_records').update(fields).eq('id',existing.id).eq('revision',revision??existing.revision).select():await cloud.from('mba_os_records').insert({...fields,key,owner:user.id}).select();if(result.error||!result.data?.length){setStatus(result.error?.message||'另一设备已更新，请刷新后再保存 / Changed on another device. Refresh before saving.');return false;}await refresh();return true;}catch(error){setStatus('未保存 / Not saved: '+(error as Error).message);return false;}}
 async function remove(record:RecordItem){try{if(!cloud||!user){const saved:RecordItem[]=JSON.parse(localStorage.getItem(workspaceKey)||'[]');if(saved.find(r=>r.id===record.id)?.revision!==record.revision)throw Error('Changed in another tab');localStorage.setItem(workspaceKey,JSON.stringify(saved.filter(r=>r.id!==record.id)));await refresh();return true;}const result=await cloud.from('mba_os_records').delete().eq('id',record.id).eq('revision',record.revision).select();if(result.error||!result.data?.length)throw Error('Delete failed');await refresh();return true;}catch{setStatus('删除未完成，请刷新 / Delete failed; refresh');return false;}}
 return <Context.Provider value={{user,ownerId:user?.id||localOwner,records,ready,status,member,refresh,put,remove}}>{children}</Context.Provider>;
}
export function useWorkspace(){const value=useContext(Context);if(!value)throw Error('WorkspaceProvider missing');return value;}
